const funFacts = [
  'Never skips leg day',
  'Can pickpocket someone while looking them in the eye',
  'Has a pet owl named Merlin',
  'Makes her own arrows from enchanted wood',
  'Can arm-wrestle a troll and win',
  'Has converted three demons back to the light',
  'Memorized an entire library of spells',
  "Once survived a dragon's fire breath",
  'Cooks gourmet meals with a campfire',
  'Trained by a legendary swordmaster',
  'Fought in a war and lived to tell the tale',
  'Won a duel against an unbeatable foe',
  'Has an uncanny knack for animal handling',
  'Can talk their way out of any situation',
  'Has never lost a game of chance',
  'Knows the secret paths of the forest',
  'Fluent in six languages, including Draconic',
  "Wears an enchanted amulet that they don't know is enchanted",
  'Hates the taste of healing potions',
  'Can brew potions that even wizards find perplexing',
  "Carries a mysterious scroll they can't yet read",
  'Believes in a deity that no one else has heard of',
  'Owns a rare artifact that they use as a paperweight',
  'Always knows which way is north',
  'Can read people like an open book',
  'Has a tattoo with magical properties',
  'Skilled in the arts of stealth and subterfuge',
  'Once saved a village from a rampaging monster',
  'Was a blacksmith before taking up adventuring',
  'Inherits their skills from a legendary hero',
  'Can recognize any poison on sight',
  'Carries a lucky charm given by a fortune teller',
  'Refuses to use any weapons, relying on hand-to-hand combat',
  'Has a soft spot for underdogs and will always help them',
  'Never sleeps, but meditates deeply',
  'Writes a journal every night detailing their adventures',
  'Collects rare books and manuscripts',
  'Always has an inspirational quote for every occasion',
  'Skilled in the arts of diplomacy and negotiation',
  'Mastered the rare technique of dual-wielding shields',
  'Once outdrank a dwarf in a tavern competition',
  'Is oddly proficient at mundane tasks like knitting and cooking',
  'Is unknowingly the heir to a forgotten kingdom',
  'Is writing an epic poem about their travels',
  'Climbed the tallest mountain just to see the sunrise',
  'Solves complex puzzles for fun',
  "Is afraid of the dark, but won't admit it",
  'Has an identical twin who is their polar opposite',
  'Has a phobia of magical constructs',
  'Is a polymath, excelling in various disciplines',
  "Invented a new spell that's become quite popular",
  'Is on a first-name basis with multiple royalty',
  "Doesn't believe in magic, despite using it",
  "Can mimic any sound or voice they've heard",
  'Crafts beautiful jewelry in their spare time',
  'Travels the world to taste every kind of food and drink',
  'Never forgets a face or name',
  'Can play multiple musical instruments',
  'Aspires to be a famous historian',
  'Is always the last to leave a party',
  "Has a pet rock named 'Stony'",
  "Believes they're haunted by an ancestral spirit",
  'Is searching for the ultimate culinary ingredient',
  'Has an insatiable curiosity that sometimes gets them into trouble',
  'Collects magical artifacts, but never uses them',
  'Has an extensive knowledge of ancient lore',
  'Claims to have been abducted by fey creatures',
  'Has been to another plane of existence and back',
  'Is an expert in ancient runes and sigils',
  'Is a cartographer, mapping out uncharted lands',
  'Is a natural born leader but prefers a solitary life',
  'Enjoys stargazing and can name all the constellations',
  'Speaks in riddles and proverbs',
  'Is an adrenaline junkie, always seeking the next thrill',
  'Loves to dance but has two left feet',
  'Has an affinity for magical beasts',
  'Owns a locket with a picture of a lost loved one',
  'Has a secret identity as a famous novelist',
  'Is always punctual, thanks to a magical pocket watch',
  'Can recite epic tales from memory',
  'Is a notorious prankster',
  'Is always followed by a stray animal they befriended',
  'Has solved the unsolvable riddle of an ancient sphinx',
  'Always keeps their promises, no matter the cost',
  "Is convinced they're invincible (they're not)",
];

export default funFacts;
